### ISSUE TITLE
@FeignClient custom configuration doesn't seem to take effect

### ISSUE THREAD

**Issue by eacdy** [spring-cloud/spring-cloud-netflix#1400]
I have two feign client class in my project,one is PersonClient,and the other one is StoreClient.
I want to config each of them with two configuration classes.
Here below is the source code.
```
@FeignClient(name = "personClient",serviceId = "person-service",configuration = PersonFeignConfig.class)
//@FeignClient(name = "person-service",fallback = PersonHystrixCommand.class)
public interface PersonClient {
    @RequestMapping("/person/say")
    String say(@RequestParam("word") String word);

    @RequestMapping("/person/sayError")
    String sayError();

    @RequestMapping("/person/sayHi")
    String sayHi();
}
```
the config class is 

```
public class PersonFeignConfig {
	private Logger LOGGER = LoggerFactory.getLogger(PersonFeignConfig.class);

	@Bean
	@Scope("prototype")
	Request.Options options() {
		LOGGER.info("PERSON FEIGN CONFIG ");
		return new Request.Options(1, 1);
	}
}
```

=======

```
@FeignClient(name = "personClient",serviceId = "person-service",configuration = PersonFeignConfig.class)
//@FeignClient(name = "person-service",fallback = PersonHystrixCommand.class)
public interface PersonClient {

    @RequestMapping("/person/say")
    String say(@RequestParam("word") String word);
    
    @RequestMapping("/person/sayError")
    String sayError();
    
    @RequestMapping("/person/sayHi")
    String sayHi();
}
```

configuration class is

```
@Configuration
public class StoreFeignConfig {
	private Logger LOGGER = LoggerFactory.getLogger(StoreFeignConfig.class);

	@Bean
	@Scope("prototype")
	@Primary
	Request.Options options2() {
		LOGGER.info("STORE FEIGN CONFIG");
		return new Request.Options(5000, 5000);
	}
}
```

In my opinion, call PersonClient should not get response.because i've configed the connectTimeoutMillis 1ms and readTimeoutMillis 1ms.
but it always returns response code 200.

CODE URL: https://github.com/eacdy/test
WHAT's wrong with the code?Could you help me?

**Comment by bilak** [comment]
try to put those configuration classes out of application's `@ ComponentScan`.

From [documentation](http://cloud.spring.io/spring-cloud-netflix/spring-cloud-netflix.html)

> The FooConfiguration has to be @Configuration but take care that it is not in a @ComponentScan for the main application context, otherwise it will be used for every @FeignClient. If you use @ComponentScan (or @SpringBootApplication) you need to take steps to avoid it being included (for instance put it in a separate, non-overlapping package, or specify the packages to scan explicitly in the @ComponentScan).

**Comment by eacdy** [comment]
@bilak  I've moved the two config classes, it still wouldn't work

**Comment by ryanjbaxter** [comment]
Can you show us how you moved it out of your application's component scan?  Something that can be a little tricky.

**Comment by eacdy** [comment]
I've moved the two config classes .
CODE URL: https://github.com/eacdy/test

**Comment by spencergibb** [comment]
@eacdy `serviceId` is deprecated and have both is causing problems.
```
@FeignClient(name = "personClient",serviceId = "person-service",configuration = PersonFeignConfig.class)
```
should be changed to:
```
@FeignClient(name = "person-service",configuration = PersonFeignConfig.class)
```

**Comment by eacdy** [comment]
@spencergibb thank you very much, problems are resolved.

**Comment by luny52** [comment]
I have a similar problem.

 I have two different feign client class but feign name is same(call the same  one  service),After seeing this article,I've moved the two config classes,but the problem remains.

and I try to modify use using two non feign names,the problem has been solved.

so? call the same  one  service must be used a same config classes??

**Comment by ryanjbaxter** [comment]
@luny52 I dont see how you problem is similar.  Please open a separate issue with your question as well as an example project.

**Comment by luny52** [comment]
@ryanjbaxter   ok
